### ISSUE TITLE
What does it mean that SearchIndex cannot be updated?

### ISSUE THREAD

**Issue by innerop** [ekzhu/SetSimilaritySearch#3]
Hi,

Interesting work. I'd like to evaluate it for my use case. However, I am not getting what you mean by "Search index cannot be updated."  Are you saying that it cannot be updated at all (maybe blow up the database and do over?) or that it has no update method? What if I update the sets and then create the index again? That would be creating a brand new index. To me, that's a method of updating.

Please clarify. 

Thanks so much,

**Comment by ekzhu** [comment]
Hi, yes by your definition of update the index can be updated through rebuilding from the data.

It is theoretically possible to have an "in-place" update method for the SearchIndex without rebuilding, but I haven't gotten time to implement it.

**Comment by innerop** [comment]
yeah, sorry I didn't understand at first. Might be worth it to add "in-place" to the Readme unless most people assume that's what is meant =)
